[package]
name = "uhr"
version = "0.1.0"
authors = ["eroy"]
edition = "2018"

[dependencies]
lazy_static = "*"
error-chain = "0.12.4"
reqwest = "0.11"
tokio = { version = "1.2", features = ["full"] }

[build-dependencies]
bindgen = "*"

