FROM golang:1.15-windowsservercore-ltsc2016

WORKDIR /workspace

ENV OUT_DIR=./unity/Assets/Plugins/Editor

CMD mkdir -p $OUT_DIR \
    GOOS=windows GOARCH=amd64 \
        go build -ldflags="-s -w" -buildmode c-shared -o $OUT_DIR/UnityHttpRequests-amd64.dll ./uhr/go/cmd/uhr/ && \
    rm -f $OUT_DIR/UnityHttpRequests-amd64.h
