FROM golang:1.15-alpine

RUN apk add build-base && \
    rm -rf /var/cache/apk/*

WORKDIR /workspace

ENV OUT_DIR=./unity/Assets/Plugins/Editor

CMD mkdir -p $OUT_DIR && \
    GOOS=linux GOARCH=amd64 \
        go build -ldflags="-s -w" -buildmode c-shared -o $OUT_DIR/libUnityHttpRequests-amd64.so ./uhr/go/cmd/uhr/ && \
    rm -f $OUT_DIR/libUnityHttpRequests-amd64.h
