FROM mcr.microsoft.com/dotnet/sdk:5.0

#ENV LD_DEBUG="all"
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/workspace/Assets/Plugins/Editor"

WORKDIR /workspace
COPY ./unity .

RUN echo "<Project><PropertyGroup><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup></Project>" > Directory.Build.props && \
    dotnet new classlib -o Runtime -n UnityHttpRequests.Runtime -f netstandard2.0 --no-restore && \
    dotnet new nunit -o Tests/Runtime -n UnityHttpRequests.Tests.Runtime --no-restore && \
    dotnet add Tests/Runtime/UnityHttpRequests.Tests.Runtime.csproj reference Runtime/UnityHttpRequests.Runtime.csproj && \
    dotnet new sln -n UnityHttpRequests && \
    dotnet sln UnityHttpRequests.sln add Runtime/UnityHttpRequests.Runtime.csproj && \
    dotnet sln UnityHttpRequests.sln add Tests/Runtime/UnityHttpRequests.Tests.Runtime.csproj && \
    dotnet test --list-tests

CMD dotnet test --no-build --no-restore --logger:console --verbosity=n