find_path(MBEDTLS_INCLUDE_DIRS mbedtls/ssl.h PATHS ${CMAKE_INSTALL_PREFIX} NO_DEFAULT_PATH)
find_library(MBEDTLS_LIBRARY mbedtls PATHS ${CMAKE_INSTALL_PREFIX} NO_DEFAULT_PATH)
find_library(MBEDX509_LIBRARY mbedx509 PATHS ${CMAKE_INSTALL_PREFIX} NO_DEFAULT_PATH)
find_library(MBEDCRYPTO_LIBRARY mbedcrypto PATHS ${CMAKE_INSTALL_PREFIX} NO_DEFAULT_PATH)

set(MBEDTLS_LIBRARIES "${MBEDTLS_LIBRARY}" "${MBEDX509_LIBRARY}" "${MBEDCRYPTO_LIBRARY}")
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MBEDTLS DEFAULT_MSG MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)
mark_as_advanced(MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)
