name: Build unity plugins
on:
  push:
    branches:
      - release

jobs:

  build-plugin-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          bash scripts/build_ios.sh
          ls -alR .prefix

  build-plugin-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - shell: bash
        run: |
          UHR_NDK_ROOT="${{ steps.setup-ndk.outputs.ndk-path }}" bash scripts/build.sh
          ls -alR .prefix

  build-plugin-editor-linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          bash scripts/build.sh
          ls -alR .prefix

  build-plugin-editor-win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # Use VS developer command prompt so nmake is available
      - uses: ilammy/msvc-dev-cmd@v1
      - run: |
          bash scripts/build.sh
          ls -alR .prefix
