name: Build unity plugins
on: [push]

jobs:

  build-plugin-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          bash ./scripts/build-ios.sh
          ls -alR ./.prefix

  build-plugin-android:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d
      - name: Build
        shell: bash
        run: |
          NDK_ROOT="${{ steps.setup-ndk.outputs.ndk-path }}" bash ./scripts/build-android.sh
          ls -alR ./.prefix

  build-plugin-editor-linux64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          bash ./scripts/build-linux64.sh
          ls -alR ./.prefix

  build-plugin-editor-win64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # Use VS developer command prompt so nmake is available
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: bash
        run: |
          bash ./scripts/build-win64.sh
          ls -alR ./.prefix
